site_name: Salt AI Docs
site_url: https://docs.getsalt.ai
theme:
  name: material
  logo: images/salt-word@2x.png
  favicon: images/favicon-light.png
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.indexes
    - navigation.top
    - navigation.footer
    - toc.integrate
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
markdown_extensions:
  - tables
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji ''
      emoji_generator: !!python/name:material.extensions.emoji.to_svg ''
  - pymdownx.highlight:
      anchor_linenums: true
      pygments_lang_class: true
      line_spans: __span
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - def_list
  - toc:
      permalink: true
  - pymdownx.keys
  - attr_list
  - md_in_html
extra_css:
  - stylesheets/theme.css
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/get-salt-AI
      name: Salt Github
    - icon: fontawesome/brands/discord
      link: https://discord.gg/saltai
      name: Salt Discord
  analytics:
    provider: google
    property: G-MHLEW2T4PQ

plugins:
  - search
  - tags
  - social:
      cache: false
      cards_layout_options:
        font_family: Inter
        background_color: '#C0BED3'
        color: black
nav:
  - Announcing Salt v1.0: salt-v1-announcement.md
  - Migrating to Salt v1.0: v1-migration-guide.md
  - Getting Started: index.md
  - Nodes:
    - Nodes: nodes/index.md
    - Text: nodes/text.md
    - LLMs: nodes/llms.md
